Running through the testing instructions (#32)
* Running through the testing instructions

* I like `python3 -m venv` instead of `virtualenv` since the former comes out of the box with Python
* Looks like you have to be in the `.venv` directory for anything to work, otherwise:

```
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

* Whitespace

* A few suggestions for README.md